---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
dotfiles_repo: https://github.com/emartin-hv/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Source/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .osx
  - .vimrc

configure_terminal: false

configure_osx: true
osx_script: "~/.osx --no-restart"

configure_sudoers: true
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  - amazon-ecs-cli
  - ansible-lint
  - awscli
  - azure-cli
  - bash-completion
  - coreutils
  - eksctl
  - gettext
  - git
  - github/gh/gh
  - helm
  - hub
  - jq
  - k9s
  - kubectx
  - kubernetes-cli
  - kustomize
  - lftp
  - maven
  - minikube
  - openjdk
  - openssl
  - ssh-copy-id
  - tektoncd-cli
  - tree
  - watch
  - vault
  - wget
  - xz
  - yq
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - backblaze
  - docker
  - google-chrome
  - handbrake
  - iterm2
  - lens
  - licecap
  - microsoft-office
  - openemu
  - quicken
  - slack
  - visual-studio-code
  - vagrant
  - vivaldi
  - vlc
  - wireshark
  - zoom

mas_email: ""
mas_password: ""
mas_installed_apps:
  - { id: 1333542190, name: "1Password" }
  - { id: 1346203938, name: "OmniFocus" }
  - { id: 1116599239, name: "NordVPN IKE" }
  - { id: 425424353, name: "The Unarchiver" }

pip_packages:
  - name: mkdocs
  - name: pyyaml

configure_dock: true
dockitems_remove:
  - 'App Store'
  - Calendar
  - Contacts
  - FaceTime
  - Keynote
  - Launchpad
  - News
  - Numbers
  - Pages
  - Podcasts
  - TV
  - Reminders
  - 'System Preferences'
dockitems_persist:
  - name: "OmniFocus"
    path: "/Applications/OmniFocus.app/"
    pos: 5
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 6
  - name: "Quicken"
    path: "/Applications/Quicken.app/"
    pos: 7
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 8

